export const ROUTES = {
  home: "/",
  app: "/app",
  connectBluetooth: "/connect/bluetooth",
  connectUnsupported: "/connect/unsupported",
  connectWifi: "/connect/wifi",
  connecting: "/connecting",
  about: "/about",
  faq: "/faq",
  support: "/support",
  landlinkOne: "/landlink-one",
  landlinkModuleI: "/landlink-module-i",
  landlinkModuleIBuy: "/landlink-module-i/buy",
  landlinkFirmware: "/landlink-firmware",
  hardwareSetup: "/hardware-setup",
  privacy: "/privacy",
  terms: "/terms",
  lists: "/lists",
  map: "/map",
  deviceDashboard: "/device",
  channels: "/channels",
  channelChat: "/channels/:index",
  dmChat: "/dm/:nodeIdHex",
  settings: "/settings",
  settingsTheme: "/settings/theme",
  settingsDebug: "/settings/debug",
  settingsReset: "/settings/reset",
  settingsRegion: "/settings/region",
  error: "/error",
  notFound: "*",
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
